codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 80%
    patch: off